#!/usr/bin/env bash

availableDisks=($(diskutil list | grep -E '^ {3}\d+:.*disk\d+s' | sed 's/.* [KMGT]B *//'))
diskAmount=${#availableDisks[@]}

targetUuid=D9D07274-930F-455E-B627-366FC60122E8

for (( ; diskAmount-- ; )); do
    uuid=$(diskutil info ${availableDisks[$diskAmount]} | grep 'Disk / Partition UUID:' | cut -d : -f 2 | sed 's/^ *//')
    if [[ $uuid == $targetUuid ]]; then
        currentDisk=/dev/${availableDisks[$diskAmount]}
        volumeName=$(diskutil info $currentDisk | grep 'Volume Name:' | cut -d : -f 2 | sed 's/^ *//')
        break
    fi
done

if ! mount | grep $currentDisk | grep macfuse &> /dev/null; then         #assume macfuse means it's not mounted by macOS's stock ntfs driver
    diskutil unmount $currentDisk &> /dev/null
    /usr/local/bin/ntfs-3g -o volname=$volumeName $currentDisk /Volumes/$volumeName
fi
